### ISSUE TITLE
[BUG]:  naming convection - generating names like keywords

### ISSUE THREAD

**Issue by dorotaphanSiili** [apigear-io/template-cpp14#103]
### Description of the bug

I got error
`error: expected unqualified-id before 'switch'`
for interface which had a property switch
in `examples/appthreadsafe/main.cpp`
`auto switch = someIf->getSwitch()`

but the problem is general, we can stumble across it in other places too
I'd suggest to add prefixed like l_ for local variables, in for incoming etc.

**Second variant of issue**
issue for generated api, and other features when the property is really "switch", not a "Switch" which was present in VSS code

### Steps To Reproduce

1.create an interface with  property Switch
2. generate code with example feautre
3. try to build in examples/appthreadsafe/main.cpp

**Second variant of issue**
1.create an interface with  property switch
2. generate code with any feature
3. try to build api

**Comment by jryannel** [comment]
See https://github.com/apigear-io/cli/issues/107

**Comment by dorotaphanSiili** [comment]
first variant solved with https://github.com/apigear-io/template-cpp14/commit/3b23f1030ca7a11e346d80da0d985a30a6fadb2e
second variant solved with https://github.com/apigear-io/cli/issues/107
What is left is to add a keyword to a goldenmaster

**Comment by dorotaphanSiili** [comment]
the missing part is moved to issue https://github.com/apigear-io/cli/issues/122
