### ISSUE TITLE
[BUG] adding a client when source is not added

### ISSUE THREAD

**Issue by dorotaphanSiili** [apigear-io/template-cpp14#57]
server is up and running, but registry does not have yet the source. Both remote node and remote registry don't successfully process link message.
The connection is set up so  client side won't retry connection, but link message should be send again.
The solution would be
- [x]  service discovery - sending request only when service is available -> extracetd to ticket https://github.com/apigear-io/template-cpp14/issues/144

- [x]  storing sent requests for which we didn't got init message back. Those need to be re-send with some repeat time period -> Decided that we won't do that 
- [x] add separate ticket to make sure set up process is proper https://github.com/apigear-io/template-cpp14/issues/145

**Comment by w4bremer** [comment]
This more of a olink protocol change, right?
All implementations should behave similar.

**Comment by dorotaphanSiili** [comment]
depends- service discovery yes
server storing request until they are handled (or with some timeout) and init sent back - doesn't change olink

**Comment by w4bremer** [comment]
On the two separate issues:

1.  This is a different feature request adding a zeroconf on top of olink -> create new issue
2. Make sure documentation, tests and examples only start listening on the server side once all sources are set up
